---
title: "hw5_tdolkar"
author: "Tsering Dolkar"
date: "10/26/2020"
output: pdf_document
latex_engine: xelatex
html_document:
df_print: paged
header-includes: \usepackage{tikz,pgfplots} \usepackage{fancyhdr}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H', fig.align = "center", echo = TRUE, include = FALSE, eval = TRUE, cache = TRUE)
library(data.table)
library(tidyverse)
library(ggplot2)
library(qwraps2)
library(car)
library(ggpubr)
library(multipanelfigure)
library(VGAM)
```

## Problem 1. 
Worked through the Swirl ``Exploratory\_Data\_Analysis'' lesson parts 1-10.

## Problem 2. 
Created the Rmd file

## Problem 3. 
```{r data_import, cache=FALSE, include=TRUE, echo=TRUE, warning=F}
## getting http://databank.worldbank.org/data/download/Edstats_csv.zip

#read in data, looks like csv dump, blah
data_raw <- read.csv('EdStatsData.csv', sep = ",")
```

```{r correct_header, include=T}
destroyX = function(es) {
  f = es
  for (i in c(1:length(f))){ #for each value in Year
    if (startsWith(f[i], "X") == TRUE)  { #if starts with 'X' ..
      f[i] <- substr(f[i], 2, 100) #get rid of it
    }
  }
  return(f)
}
```

```{r tidy_data, include=T}
tidy_data <- data_raw %>% 
  gather(key = "Year", value = "Data", 5:70)
tidy_data$Year <- destroyX(tidy_data$Year)
tidy_data <- na.omit(tidy_data)
completeDataset_dataPoints <- dim(data_raw)
completeDataset_dataPoints
cleanedDataset_dataPoints <- dim(tidy_data)
cleanedDataset_dataPoints

chosenCountries <- tidy_data %>% 
  filter(Country.Code == "EMU"| Country.Code == "ECS")
summary_stat <- by(chosenCountries, chosenCountries$Indicator.Name, summary)
length(summary_stat)
head(summary_stat)
```

## Problem 4.
```{r data,include=T}
options(scipen = 0)
options(digits = 2)

par(mfrow=c(2,3))

lmfit <- lm(chosenCountries$Data ~ chosenCountries$Year)

plot(fitted(lmfit),residuals(lmfit),pch=16,xlab = "Predicted Value", ylab = "Residual")
abline(h = 0)

plot(fitted(lmfit),rstudent(lmfit),pch=16,xlab = "Predicted Value", ylab = "Rstudent")

plot(hatvalues(lmfit), rstudent(lmfit), pch = 16, xlab="Leverage", ylab = "Rstudent")

qqnorm(residuals(lmfit), ylab = "Residuals", pch = 16)
qqline(residuals(lmfit))

lmfitw <- lm(abs(residuals(lmfit)) ~ chosenCountries$Year)
w <- 1/abs(fitted(lmfitw))
yw <- w^0.5*chosenCountries$Data
plot(fitted(lmfitw), w, pch=16, xlab = "Predicted Value", ylab = "Weight")


plot(chosenCountries$Data, cooks.distance(lmfit),pch=16, xlab = "Observation", ylab = "Cook's D", type = c("b"))
```

## Problem 5.
```{r ggplot_version, include=T}

p1 <- ggplot(chosenCountries, aes(x=fitted(lmfit), y=residuals(lmfit), color="red")) +
      geom_point() +
      geom_hline(yintercept = 0) +
      labs(x = "Predicted Value", y = "Residual") +
      theme(axis.text.x = element_text(angle = 90, size = 5,
                                   vjust = 0.6),legend.position = "none")

p2 <-ggplot(chosenCountries, aes(x=fitted(lmfit), y=rstudent(lmfit), color="red")) +
     geom_point() +
     labs(x = "Predicted Value", y = "Rstudent") +
     theme(axis.text.x = element_text(angle = 90, size = 5,
                                   vjust = 0.6),legend.position = "none")

p3 <-ggplot(chosenCountries, aes(x=hatvalues(lmfit), y=rstudent(lmfit), color="red")) +
     geom_point() +
     labs(x = "Leverage", y = "Rstudent") +
     theme(axis.text.x = element_text(angle = 90, size = 5,
                                   vjust = 0.6),legend.position = "none")

p4 <-ggplot(chosenCountries, aes(sample=residuals(lmfit), color = "red")) +
     stat_qq() +
     stat_qq_line(line.p = c(0.25, 0.75)) +
     labs(y = "Residual") +
     theme(legend.position = "none")

p5 <-ggplot(chosenCountries, aes(x=fitted(lmfit), y= w, color="red")) +
     geom_point() +
     geom_hline(yintercept = 0) +
     labs(x = "Predicted Value", y = "Weight") +
     theme(axis.text.x = element_text(angle = 90, size = 5,
                                   vjust = 0.6),legend.position = "none")

p6 <-ggplot(chosenCountries, aes(x=Data, y= cooks.distance(lmfit), color="red")) +
     geom_line() +
     geom_point() +
     geom_hline(yintercept = 0) +
     labs(x = "Observation", y = "Cook's D") +
     theme(axis.text.x = element_text(angle = 90, size = 5,
                                   vjust = 0.6),legend.position = "none")

figure1 <- multi_panel_figure(columns = 3, rows = 2, panel_label_type = "none")
figure1 %<>%
  fill_panel(p1, column = 1, row = 1) %<>%
  fill_panel(p2, column = 2, row = 1) %<>%
  fill_panel(p3, column = 3, row = 1) %<>%
  fill_panel(p4, column = 1, row = 2) %<>%
  fill_panel(p5, column = 2, row = 2) %<>%
  fill_panel(p6, column = 3, row = 2)
figure1
```
